/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    'fifth-edition-character': FifthEditionCharacter;
    media: Media;
  };
  globals: {};
}
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface FifthEditionCharacter {
  id: string;
  name?: string;
  users?: string | User;
  picture?: string | Media;
  AbilityScoresAndSkills: {
    AbilityScores: {
      Intelligence?: number;
      Wisdom?: number;
      Charisma?: number;
      Dexterity?: number;
      Strength?: number;
      Constitution?: number;
    };
    IntelligenceSkills: {
      Arcana: {
        Proficient?: boolean;
        Bonus?: number;
      };
      History: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Investigation: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Nature: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Religion: {
        Proficient?: boolean;
        Bonus?: number;
      };
    };
    WisdomSkills: {
      AnimalHandling: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Insight: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Medicine: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Perception: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Survival: {
        Proficient?: boolean;
        Bonus?: number;
      };
    };
    CharismaSkills: {
      Deception: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Intimidation: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Performance: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Persuasion: {
        Proficient?: boolean;
        Bonus?: number;
      };
    };
    DexteritySkills: {
      Acrobatics: {
        Proficient?: boolean;
        Bonus?: number;
      };
      SleightOfHand: {
        Proficient?: boolean;
        Bonus?: number;
      };
      Stealth: {
        Proficient?: boolean;
        Bonus?: number;
      };
    };
  };
  Character: {
    OverallLevel: number;
    XP?: number;
    ProficiencyBonus?: number;
    ArmorClass?: number;
    Speed?: number;
    Inspiration?: boolean;
    Classes: {
      Class?:
        | 'artificer'
        | 'barbarian'
        | 'bard'
        | 'blood-hunter'
        | 'cleric'
        | 'druid'
        | 'fighter'
        | 'monk'
        | 'paladin'
        | 'ranger'
        | 'rogue'
        | 'sorcerer'
        | 'warlock'
        | 'wizard'
        | 'custom';
      Levels?: number;
      id?: string;
    }[];
    Alignment?:
      | 'lawful-good'
      | 'neutral-good'
      | 'chaotic-good'
      | 'lawful-neutral'
      | 'true-neutral'
      | 'chaotic-neutral'
      | 'lawful-evil'
      | 'neutral-evil'
      | 'chaotic-evil';
    Background?:
      | 'acolyte'
      | 'anthropologist'
      | 'archaeologist'
      | 'athlete'
      | 'charlatan'
      | 'city-watch'
      | 'clan-crafter'
      | 'cloistered-scholar'
      | 'courtier'
      | 'criminal'
      | 'entertainer'
      | 'faceless'
      | 'faction-agent'
      | 'far-traveler'
      | 'feylost'
      | 'fisher'
      | 'folk-hero'
      | 'gladiator'
      | 'guild-artisan'
      | 'guild-merchant'
      | 'haunted-one'
      | 'hermit'
      | 'house-agent'
      | 'inheritor'
      | 'investigator-(scag)'
      | 'investigator-(vrgr)'
      | 'knight'
      | 'knight-of-the-order'
      | 'marine'
      | 'mercenary-veteran'
      | 'noble'
      | 'outlander'
      | 'pirate'
      | 'sage'
      | 'sailor'
      | 'shipwright'
      | 'smuggler'
      | 'soldier'
      | 'spy'
      | 'urban-bounty-hunter'
      | 'urchin'
      | 'uthgardt-tribe-member'
      | 'waterdhavian-noble'
      | 'witchlight-hand'
      | 'black-fist-double-agent'
      | 'dragon-casualty'
      | 'iron-route-bandit'
      | 'phlan-insurgent'
      | 'stojanow-prisoner'
      | 'ticklebelly-nomad'
      | 'caravan-specialist'
      | 'earthspur-miner'
      | 'harborfolk'
      | 'mulmaster-aristocrat'
      | 'phlan-refugee'
      | 'cormanthor-refugee'
      | 'gate-urchin'
      | 'hillsfar-merchant'
      | 'hillsfar-smuggler'
      | 'secret-identity'
      | 'shade-fanatic'
      | 'trade-sheriff'
      | 'gate-warden'
      | 'giant-foundling'
      | 'knight-of-solamnia'
      | 'mage-of-high-sorcery'
      | 'planar-philosopher'
      | 'rune-carver'
      | 'ashari'
      | "celebrity-adventurer's-scion"
      | 'failed-merchant'
      | 'gambler'
      | 'plaintiff'
      | 'rival-intern'
      | 'dissenter'
      | 'initiate'
      | 'vizier'
      | 'inquisitor'
      | 'azorius-functionary'
      | 'boros-legionnaire'
      | 'dimir-operative'
      | 'golgari-agent'
      | 'gruul-anarch'
      | 'izzet-engineer'
      | 'orzhov-representative'
      | 'rakdos-cultist'
      | 'selesnya-initiate'
      | 'simic-scientist'
      | 'lorehold-student'
      | 'prismari-student'
      | 'quandrix-student'
      | 'silverquill-student'
      | 'witherbloom-student'
      | 'grinner'
      | 'volstrucker-agent'
      | 'astral-drifter'
      | 'wildspacer';
    Age?: number;
    Height?: string;
    Weight?: string;
    size?: 'tiny' | 'small' | 'medium' | 'large' | 'huge' | 'gargantuan';
    Eyes?: string;
    Hair?: string;
    skin?: string;
    Clothes?: string;
    Other?: string;
    Languages?: string;
    Proficiencies?: string;
  };
  createdAt: string;
  updatedAt: string;
}
export interface Media {
  id: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes: {
    thumbnail: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    card: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    tablet: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
  createdAt: string;
  updatedAt: string;
}
